import {
  Activity,
  Blend,
  Bot,
  Boxes,
  BrainCircuit,
  Cloud,
  Container,
  Database,
  DoorOpen,
  FileJson,
  GitFork,
  Globe2,
  HardDrive,
  KeyRound,
  ListEnd,
  Monitor,
  Radio,
  RadioTower,
  Route,
  Scale,
  ScanSearch,
  SearchCode,
  Server,
  Smartphone,
  Unplug,
  UserRound,
  Vault,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  user: UserRound,
  browser: Globe2,
  "mobile-app": Smartphone,
  "external-client": Unplug,
  dns: Route,
  cdn: Cloud,
  "load-balancer": Scale,
  "api-gateway": DoorOpen,
  "frontend-app": Monitor,
  "backend-service": Server,
  microservice: Boxes,
  "serverless-function": Zap,
  "kubernetes-cluster": Container,
  "relational-database": Database,
  "document-database": FileJson,
  cache: Activity,
  "vector-database": ScanSearch,
  "object-storage": HardDrive,
  queue: ListEnd,
  "event-broker": RadioTower,
  "pub-sub-topic": Radio,
  "event-stream": Waves,
  "hosted-llm": BrainCircuit,
  "embedding-model": Blend,
  "ai-agent": Bot,
  "retrieval-service": SearchCode,
  "identity-provider": KeyRound,
  "secrets-manager": Vault,
  repository: GitFork,
  observability: Activity,
};

export function SemanticCatalogIcon({ semanticType, size = 18, className }: { semanticType: string; size?: number; className?: string }) {
  const Icon = icons[semanticType] ?? Boxes;
  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={1.8} />;
}
