import { NodeDefinition } from "./types";

export const PRODUCTION_NODE_TYPES = [
  "promptNode",
  "llmNode",
  "agentNode",
  "embedNode",
  "rerankNode",
  "extractNode",
  "classifyNode",
  "summarizeNode",
  "evaluatorNode",
  "memoryNode",
  "routerNode",
  "apiGatewayNode",
  "httpRequestNode",
  "webhookNode",
  "serviceNode",
  "functionNode",
  "schedulerNode",
  "postgresNode",
  "mongoNode",
  "redisNode",
  "vectorStoreNode",
  "queuePublishNode",
  "queueConsumeNode",
  "objectStorageNode",
  "retryNode",
  "timeoutNode",
  "circuitBreakerNode",
  "rateLimiterNode",
  "fallbackNode",
  "idempotencyNode",
  "authNode",
  "rbacNode",
  "secretsNode",
  "piiRedactionNode",
  "logNode",
  "metricNode",
  "traceNode",
  "alertNode",
  "assertionNode",
  "loadGeneratorNode",
  "faultInjectorNode",
  "testFixtureNode",
  "outputNode",
] as const;

export type ProductionNodeType = (typeof PRODUCTION_NODE_TYPES)[number];

const modelOptions = [
  { label: "Gemma 4 26B A4B", value: "google/gemma-4-26b-a4b-it" },
  { label: "Gemma 4 31B", value: "google/gemma-4-31b-it" },
  { label: "Gemma 4 26B A4B Free", value: "google/gemma-4-26b-a4b-it:free" },
  { label: "GPT-4o", value: "gpt-4o" },
  { label: "Custom / Local", value: "custom" },
];

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: "agentNode",
    title: "AI Agent",
    description: "An autonomous agent powered by Gemma 4 with tool-calling capabilities.",
    pack: "ai",
    category: "AI",
    icon: "SquareUser",
    colorClass: "bg-sky-500/10 text-sky-400 border-sky-500/30 shadow-[0_0_12px_rgba(14,165,233,0.2)]",
    inputs: [{ id: "context", label: "Context", schema: "json" }],
    outputs: [{ id: "default", label: "Response", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "AI Agent" },
      { name: "agentId", label: "Agent Config ID", type: "text", placeholder: "Select or Create an Agent" },
      { name: "systemPrompt", label: "System Prompt", type: "textarea", defaultValue: "You are a helpful workflow agent. Use tools when necessary." },
      { name: "maxIter", label: "Max Iterations", type: "number", defaultValue: 5 }
    ],
    previewFields: ["agentId", "maxIter"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "promptNode",
    title: "Prompt",
    description: "Build a structured prompt from system context and inputs.",
    pack: "ai",
    category: "AI",
    icon: "MessageSquareCode",
    colorClass: "bg-orange-500/10 text-orange-400 border-orange-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "prompt", label: "Prompt", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Prompt" },
      {
        name: "template",
        label: "Template",
        type: "textarea",
        required: true,
        placeholder: "Summarize {{default}} for the finance operations team.",
        defaultValue: "Use the following input: {{default}}",
      },
    ],
    previewFields: ["template"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "llmNode",
    title: "LLM",
    description: "Call a language model with cost and token tracking.",
    pack: "ai",
    category: "AI",
    icon: "Bot",
    colorClass: "bg-purple-500/10 text-purple-400 border-purple-500/20",
    inputs: [{ id: "prompt", label: "Prompt", schema: "text" }],
    outputs: [{ id: "default", label: "Response", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "LLM" },
      {
        name: "providerId",
        label: "Provider ID",
        type: "text",
        placeholder: "Optional saved provider ID",
      },
      {
        name: "modelId",
        label: "Model",
        type: "select",
        defaultValue: "google/gemma-4-26b-a4b-it",
        options: modelOptions,
      },
      {
        name: "customModelId",
        label: "Custom Model ID",
        type: "text",
        placeholder: "Used when Model is Custom / Local",
      },
      {
        name: "systemPrompt",
        label: "System Prompt",
        type: "textarea",
        defaultValue: "You are a production-grade system design assistant.",
      },
      {
        name: "temperature",
        label: "Temperature",
        type: "number",
        defaultValue: 0.3,
      },
      {
        name: "max_tokens",
        label: "Max Tokens",
        type: "number",
        defaultValue: 1200,
      },
      {
        name: "apiKey",
        label: "API Key Override",
        type: "password",
        placeholder: "Optional",
      },
    ],
    previewFields: ["modelId", "temperature"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "embedNode",
    title: "Embed",
    description: "Generate vector embeddings for retrieval or similarity workflows.",
    pack: "ai",
    category: "AI",
    icon: "BrainCircuit",
    colorClass: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "vector", label: "Embedding", schema: "array" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Embed" },
      {
        name: "model",
        label: "Embedding Model",
        type: "select",
        defaultValue: "text-embedding-3-small",
        options: [
          { label: "text-embedding-3-small", value: "text-embedding-3-small" },
          { label: "text-embedding-3-large", value: "text-embedding-3-large" },
        ],
      },
    ],
    previewFields: ["model"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "rerankNode",
    title: "Rerank",
    description: "Rerank candidate documents or options by relevance.",
    pack: "ai",
    category: "AI",
    icon: "ArrowUpDown",
    colorClass: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    inputs: [{ id: "default", label: "Candidates", schema: "array" }],
    outputs: [{ id: "default", label: "Ranked Results", schema: "array" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Rerank" },
      { name: "topK", label: "Top K", type: "number", defaultValue: 5 },
    ],
    previewFields: ["topK"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "extractNode",
    title: "Extract",
    description: "Extract structured entities from free text.",
    pack: "ai",
    category: "AI",
    icon: "ScanLine",
    colorClass: "bg-teal-500/10 text-teal-400 border-teal-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "default", label: "Structured Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Extract" },
      {
        name: "schemaHint",
        label: "Schema Hint",
        type: "textarea",
        placeholder: '{"customer":"string","risk":"number"}',
        defaultValue: '{"field":"value"}',
      },
    ],
    previewFields: ["schemaHint"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "classifyNode",
    title: "Classify",
    description: "Assign labels to content using rule or model semantics.",
    pack: "ai",
    category: "AI",
    icon: "Tags",
    colorClass: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "default", label: "Class", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Classify" },
      {
        name: "classes",
        label: "Classes",
        type: "textarea",
        placeholder: "high_risk\nmedium_risk\nlow_risk",
        defaultValue: "high_risk\nmedium_risk\nlow_risk",
      },
    ],
    previewFields: ["classes"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "summarizeNode",
    title: "Summarize",
    description: "Condense large context into an actionable summary.",
    pack: "ai",
    category: "AI",
    icon: "ScrollText",
    colorClass: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "default", label: "Summary", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Summarize" },
      {
        name: "style",
        label: "Style",
        type: "select",
        defaultValue: "executive",
        options: [
          { label: "Executive", value: "executive" },
          { label: "Technical", value: "technical" },
          { label: "Customer-friendly", value: "customer" },
        ],
      },
    ],
    previewFields: ["style"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "evaluatorNode",
    title: "Evaluator",
    description: "Grade output quality against criteria.",
    pack: "ai",
    category: "AI",
    icon: "Scale",
    colorClass: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [{ id: "default", label: "Evaluation", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Evaluator" },
      {
        name: "criteria",
        label: "Criteria",
        type: "textarea",
        defaultValue: "accuracy\ncompleteness\nsafety",
      },
    ],
    previewFields: ["criteria"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "memoryNode",
    title: "Memory",
    description: "Retrieve stored context or write new context.",
    pack: "ai",
    category: "AI",
    icon: "Database",
    colorClass: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    inputs: [{ id: "query", label: "Query", schema: "text" }],
    outputs: [{ id: "context", label: "Context", schema: "text" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Memory" },
      { name: "namespace", label: "Namespace", type: "text", defaultValue: "default" },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        defaultValue: "retrieve",
        options: [
          { label: "Retrieve", value: "retrieve" },
          { label: "Store", value: "store" },
        ],
      },
    ],
    previewFields: ["namespace", "mode"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "routerNode",
    title: "Router",
    description: "Route traffic to different branches based on heuristics or class.",
    pack: "ai",
    category: "AI",
    icon: "GitBranch",
    colorClass: "bg-pink-500/10 text-pink-400 border-pink-500/20",
    inputs: [{ id: "default", label: "Input", schema: "text" }],
    outputs: [
      { id: "primary", label: "Primary", schema: "text" },
      { id: "secondary", label: "Secondary", schema: "text" },
    ],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Router" },
      {
        name: "primaryKeywords",
        label: "Primary Keywords",
        type: "textarea",
        defaultValue: "priority\ncritical\nhigh",
      },
    ],
    previewFields: ["primaryKeywords"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "apiGatewayNode",
    title: "API Gateway",
    description: "Represent an ingress layer with auth and rate policies.",
    pack: "backend",
    category: "Backend",
    icon: "Shield",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "request", label: "Request", schema: "json" }],
    outputs: [{ id: "default", label: "Forwarded Request", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "API Gateway" },
      { name: "route", label: "Route", type: "text", defaultValue: "/api/v1/resource" },
      { name: "authRequired", label: "Require Auth", type: "boolean", defaultValue: false },
    ],
    previewFields: ["route"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "httpRequestNode",
    title: "HTTP Request",
    description: "Call an upstream REST endpoint or internal service.",
    pack: "backend",
    category: "Backend",
    icon: "Globe",
    colorClass: "bg-sky-500/10 text-sky-400 border-sky-500/20",
    inputs: [{ id: "body", label: "Body", schema: "json" }],
    outputs: [{ id: "default", label: "Response", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "HTTP Request" },
      { name: "testUrl", label: "Test URL", type: "text", placeholder: "https://sandbox.example.com/api" },
      { name: "url", label: "Live URL", type: "text", defaultValue: "https://example.com" },
      {
        name: "method",
        label: "Method",
        type: "select",
        defaultValue: "POST",
        options: [
          { label: "GET", value: "GET" },
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
          { label: "DELETE", value: "DELETE" },
        ],
      },
    ],
    previewFields: ["url", "method"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "webhookNode",
    title: "Webhook",
    description: "Trigger a downstream webhook from the workflow.",
    pack: "backend",
    category: "Backend",
    icon: "Zap",
    colorClass: "bg-amber-500/10 text-amber-400 border-amber-500/20",
    inputs: [{ id: "body", label: "Body", schema: "json" }],
    outputs: [{ id: "default", label: "Response", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Webhook" },
      { name: "testUrl", label: "Test Webhook URL", type: "text", placeholder: "https://sandbox.example.com/webhook" },
      { name: "url", label: "Live Webhook URL", type: "text", defaultValue: "https://hooks.example.com" },
    ],
    previewFields: ["url"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "serviceNode",
    title: "Service",
    description: "Model a microservice or internal application service.",
    pack: "backend",
    category: "Backend",
    icon: "Boxes",
    colorClass: "bg-violet-500/10 text-violet-400 border-violet-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Service" },
      { name: "serviceName", label: "Service Name", type: "text", defaultValue: "order-service" },
      { name: "testUrl", label: "Test Endpoint", type: "text", placeholder: "https://sandbox.example.com/service" },
      { name: "url", label: "Live Endpoint", type: "text", placeholder: "https://api.example.com/service" },
      { name: "latencyMs", label: "Base Latency", type: "number", defaultValue: 120 },
    ],
    previewFields: ["serviceName", "latencyMs"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "functionNode",
    title: "Function",
    description: "Run sandboxed business logic against the current payload.",
    pack: "backend",
    category: "Backend",
    icon: "Code",
    colorClass: "bg-zinc-500/10 text-zinc-300 border-zinc-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Function" },
      {
        name: "transform",
        label: "Transform",
        type: "textarea",
        defaultValue: "Return the input with audit metadata and normalized keys.",
      },
    ],
    previewFields: ["transform"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "schedulerNode",
    title: "Scheduler",
    description: "Schedule a workflow or branch on a recurring cadence.",
    pack: "backend",
    category: "Backend",
    icon: "Clock3",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Scheduled Payload", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Scheduler" },
      { name: "cron", label: "Cron", type: "text", defaultValue: "0 * * * *" },
    ],
    previewFields: ["cron"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "postgresNode",
    title: "Postgres",
    description: "Model relational storage access with SQL semantics.",
    pack: "data",
    category: "Data",
    icon: "Table2",
    colorClass: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    inputs: [{ id: "query", label: "Query", schema: "text" }],
    outputs: [{ id: "default", label: "Rows", schema: "array" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Postgres" },
      { name: "connectionString", label: "Connection String", type: "password", placeholder: "postgres://..." },
      { name: "table", label: "Table", type: "text", defaultValue: "customers" },
      {
        name: "operation",
        label: "Operation",
        type: "select",
        defaultValue: "select",
        options: [
          { label: "Select", value: "select" },
          { label: "Insert", value: "insert" },
          { label: "Update", value: "update" },
        ],
      },
    ],
    previewFields: ["table", "operation"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "mongoNode",
    title: "MongoDB",
    description: "Execute document operations against MongoDB.",
    pack: "data",
    category: "Data",
    icon: "Database",
    colorClass: "bg-green-500/10 text-green-400 border-green-500/20",
    inputs: [{ id: "default", label: "Payload", schema: "json" }],
    outputs: [{ id: "default", label: "Documents", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "MongoDB" },
      { name: "uri", label: "URI", type: "password", placeholder: "mongodb+srv://..." },
      { name: "database", label: "Database", type: "text", defaultValue: "buildrax" },
      { name: "collection", label: "Collection", type: "text", defaultValue: "workflows" },
      {
        name: "operation",
        label: "Operation",
        type: "select",
        defaultValue: "find",
        options: [
          { label: "Find", value: "find" },
          { label: "Insert One", value: "insertOne" },
          { label: "Update One", value: "updateOne" },
        ],
      },
    ],
    previewFields: ["database", "collection", "operation"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "redisNode",
    title: "Redis",
    description: "Model cache gets, sets, and invalidation behavior.",
    pack: "data",
    category: "Data",
    icon: "HardDrive",
    colorClass: "bg-red-500/10 text-red-400 border-red-500/20",
    inputs: [{ id: "default", label: "Payload", schema: "json" }],
    outputs: [{ id: "default", label: "Cache Result", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Redis" },
      { name: "url", label: "Redis URL", type: "password", placeholder: "redis://..." },
      { name: "key", label: "Key", type: "text", defaultValue: "session:customer" },
      {
        name: "operation",
        label: "Operation",
        type: "select",
        defaultValue: "get",
        options: [
          { label: "Get", value: "get" },
          { label: "Set", value: "set" },
          { label: "Invalidate", value: "invalidate" },
        ],
      },
    ],
    previewFields: ["key", "operation"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "vectorStoreNode",
    title: "Vector Store",
    description: "Search or write vectorized documents.",
    pack: "data",
    category: "Data",
    icon: "Warehouse",
    colorClass: "bg-indigo-500/10 text-indigo-400 border-indigo-500/20",
    inputs: [{ id: "default", label: "Payload", schema: "json" }],
    outputs: [{ id: "default", label: "Matches", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Vector Store" },
      { name: "endpoint", label: "Endpoint", type: "text", placeholder: "https://vector-db.example.com/query" },
      { name: "apiKey", label: "API Key", type: "password", placeholder: "Optional" },
      { name: "namespace", label: "Namespace", type: "text", defaultValue: "enterprise" },
      {
        name: "operation",
        label: "Operation",
        type: "select",
        defaultValue: "search",
        options: [
          { label: "Search", value: "search" },
          { label: "Upsert", value: "upsert" },
        ],
      },
    ],
    previewFields: ["namespace", "operation"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "queuePublishNode",
    title: "Queue Publish",
    description: "Publish a message onto a queue or topic.",
    pack: "data",
    category: "Data",
    icon: "Send",
    colorClass: "bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20",
    inputs: [{ id: "default", label: "Message", schema: "json" }],
    outputs: [{ id: "default", label: "Ack", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Queue Publish" },
      { name: "endpoint", label: "Queue Endpoint", type: "text", placeholder: "https://queue.example.com/messages" },
      { name: "apiKey", label: "API Key", type: "password", placeholder: "Optional" },
      { name: "queueName", label: "Queue", type: "text", defaultValue: "orders.created" },
    ],
    previewFields: ["queueName"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "queueConsumeNode",
    title: "Queue Consume",
    description: "Represent a worker consuming messages from a queue.",
    pack: "data",
    category: "Data",
    icon: "Inbox",
    colorClass: "bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20",
    inputs: [{ id: "default", label: "Message", schema: "json" }],
    outputs: [{ id: "default", label: "Processed", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Queue Consume" },
      { name: "endpoint", label: "Queue Endpoint", type: "text", placeholder: "https://queue.example.com/messages" },
      { name: "apiKey", label: "API Key", type: "password", placeholder: "Optional" },
      { name: "queueName", label: "Queue", type: "text", defaultValue: "orders.created" },
    ],
    previewFields: ["queueName"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "objectStorageNode",
    title: "Object Storage",
    description: "Store or read documents, exports, or artifacts.",
    pack: "data",
    category: "Data",
    icon: "FolderArchive",
    colorClass: "bg-lime-500/10 text-lime-400 border-lime-500/20",
    inputs: [{ id: "default", label: "Artifact", schema: "json" }],
    outputs: [{ id: "default", label: "Storage Result", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Object Storage" },
      { name: "endpoint", label: "Storage Endpoint", type: "text", placeholder: "https://storage.example.com/object" },
      { name: "apiKey", label: "API Key", type: "password", placeholder: "Optional" },
      { name: "bucket", label: "Bucket", type: "text", defaultValue: "buildrax-artifacts" },
    ],
    previewFields: ["bucket"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "retryNode",
    title: "Retry Policy",
    description: "Apply retry semantics to the current branch.",
    pack: "reliability",
    category: "Reliability",
    icon: "RotateCcw",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Retry Policy" },
      { name: "attempts", label: "Attempts", type: "number", defaultValue: 3 },
    ],
    previewFields: ["attempts"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "timeoutNode",
    title: "Timeout",
    description: "Enforce max allowed latency for a branch or service.",
    pack: "reliability",
    category: "Reliability",
    icon: "TimerOff",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Timeout" },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", defaultValue: 1200 },
    ],
    previewFields: ["timeoutMs"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "circuitBreakerNode",
    title: "Circuit Breaker",
    description: "Trip and recover based on failure thresholds.",
    pack: "reliability",
    category: "Reliability",
    icon: "PowerOff",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [
      { id: "closed", label: "Closed", schema: "json" },
      { id: "open", label: "Open", schema: "json" },
    ],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Circuit Breaker" },
      { name: "failureThreshold", label: "Failure Threshold", type: "number", defaultValue: 5 },
    ],
    previewFields: ["failureThreshold"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "rateLimiterNode",
    title: "Rate Limiter",
    description: "Model downstream rate control and throttling.",
    pack: "reliability",
    category: "Reliability",
    icon: "Gauge",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Rate Limiter" },
      { name: "requestsPerMinute", label: "Requests / Minute", type: "number", defaultValue: 120 },
    ],
    previewFields: ["requestsPerMinute"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "fallbackNode",
    title: "Fallback",
    description: "Provide a fallback branch or safe degraded response.",
    pack: "reliability",
    category: "Reliability",
    icon: "ShieldAlert",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [
      { id: "primary", label: "Primary", schema: "json" },
      { id: "fallback", label: "Fallback", schema: "json" },
    ],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Fallback" },
      {
        name: "fallbackMessage",
        label: "Fallback Message",
        type: "textarea",
        defaultValue: "The primary service is unavailable; serve cached or default content.",
      },
    ],
    previewFields: ["fallbackMessage"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "idempotencyNode",
    title: "Idempotency",
    description: "Prevent duplicate processing using a deterministic key.",
    pack: "reliability",
    category: "Reliability",
    icon: "Fingerprint",
    colorClass: "bg-slate-500/10 text-slate-200 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Idempotency" },
      { name: "key", label: "Key", type: "text", defaultValue: "{{requestId}}" },
    ],
    previewFields: ["key"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "authNode",
    title: "Auth Guard",
    description: "Apply authentication checks to a branch.",
    pack: "security",
    category: "Security",
    icon: "Lock",
    colorClass: "bg-zinc-500/10 text-zinc-300 border-zinc-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Authorized Input", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Auth Guard" },
      {
        name: "strategy",
        label: "Strategy",
        type: "select",
        defaultValue: "oauth",
        options: [
          { label: "OAuth", value: "oauth" },
          { label: "API Key", value: "api_key" },
          { label: "Service Token", value: "service_token" },
        ],
      },
    ],
    previewFields: ["strategy"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "rbacNode",
    title: "RBAC Policy",
    description: "Check role- or policy-based access control.",
    pack: "security",
    category: "Security",
    icon: "UserCog",
    colorClass: "bg-zinc-500/10 text-zinc-300 border-zinc-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Authorized Input", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "RBAC Policy" },
      { name: "role", label: "Required Role", type: "text", defaultValue: "admin" },
    ],
    previewFields: ["role"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "secretsNode",
    title: "Secrets",
    description: "Inject a named secret into the flow from the vault.",
    pack: "security",
    category: "Security",
    icon: "KeyRound",
    colorClass: "bg-zinc-500/10 text-zinc-300 border-zinc-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Secret-enriched Input", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Secrets" },
      { name: "secretName", label: "Secret Name", type: "text", defaultValue: "third-party-api-key" },
    ],
    previewFields: ["secretName"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "piiRedactionNode",
    title: "PII Redaction",
    description: "Redact sensitive content from text or JSON payloads.",
    pack: "security",
    category: "Security",
    icon: "ShieldCheck",
    colorClass: "bg-zinc-500/10 text-zinc-300 border-zinc-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Redacted Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "PII Redaction" },
      {
        name: "entities",
        label: "Entities",
        type: "textarea",
        defaultValue: "email\nphone\npayment_card\nssn",
      },
    ],
    previewFields: ["entities"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "logNode",
    title: "Log",
    description: "Emit structured logs for the current payload.",
    pack: "observability",
    category: "Observability",
    icon: "Logs",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Log" },
      { name: "level", label: "Level", type: "select", defaultValue: "info", options: [
        { label: "Info", value: "info" },
        { label: "Warn", value: "warn" },
        { label: "Error", value: "error" },
      ] },
    ],
    previewFields: ["level"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "metricNode",
    title: "Metric",
    description: "Publish a metric from the current branch.",
    pack: "observability",
    category: "Observability",
    icon: "Activity",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Metric" },
      { name: "metricName", label: "Metric Name", type: "text", defaultValue: "workflow.success" },
    ],
    previewFields: ["metricName"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "traceNode",
    title: "Trace",
    description: "Create or enrich a trace span for the branch.",
    pack: "observability",
    category: "Observability",
    icon: "Route",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Trace" },
      { name: "spanName", label: "Span Name", type: "text", defaultValue: "workflow.branch" },
    ],
    previewFields: ["spanName"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "alertNode",
    title: "Alert",
    description: "Raise an alert when a threshold is crossed.",
    pack: "observability",
    category: "Observability",
    icon: "BellRing",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Alert" },
      { name: "webhookUrl", label: "Alert Webhook", type: "password", placeholder: "Required for live alerts" },
      { name: "channel", label: "Channel", type: "text", defaultValue: "ops-alerts" },
    ],
    previewFields: ["channel"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "assertionNode",
    title: "Assertion",
    description: "Assert expected behavior on the branch.",
    pack: "observability",
    category: "Observability",
    icon: "CheckCircle2",
    colorClass: "bg-slate-500/10 text-slate-300 border-slate-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [
      { id: "pass", label: "Pass", schema: "json" },
      { id: "fail", label: "Fail", schema: "json" },
    ],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Assertion" },
      { name: "contains", label: "Contains", type: "text", defaultValue: "success" },
    ],
    previewFields: ["contains"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "loadGeneratorNode",
    title: "Load Generator",
    description: "Generate test traffic for scenario evaluation.",
    pack: "observability",
    category: "Testing",
    icon: "Rocket",
    colorClass: "bg-rose-500/10 text-rose-400 border-rose-500/20",
    inputs: [],
    outputs: [{ id: "default", label: "Traffic", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Load Generator" },
      { name: "requests", label: "Requests", type: "number", defaultValue: 100 },
    ],
    previewFields: ["requests"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "faultInjectorNode",
    title: "Fault Injector",
    description: "Inject latency or failure conditions during test-mode scenario evaluation.",
    pack: "observability",
    category: "Testing",
    icon: "Bug",
    colorClass: "bg-rose-500/10 text-rose-400 border-rose-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Fault Injector" },
      {
        name: "mode",
        label: "Mode",
        type: "select",
        defaultValue: "latency_spike",
        options: [
          { label: "Latency Spike", value: "latency_spike" },
          { label: "Dependency Timeout", value: "dependency_timeout" },
          { label: "Partial Outage", value: "partial_outage" },
        ],
      },
    ],
    previewFields: ["mode"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "testFixtureNode",
    title: "Test Fixture",
    description: "Provide user-authored fixture data during test-mode scenario evaluation.",
    pack: "observability",
    category: "Testing",
    icon: "PackageCheck",
    colorClass: "bg-rose-500/10 text-rose-400 border-rose-500/20",
    inputs: [{ id: "default", label: "Request", schema: "json" }],
    outputs: [{ id: "default", label: "Fixture Response", schema: "json" }],
    fields: [
      { name: "label", label: "Label", type: "text", defaultValue: "Test Fixture" },
      {
        name: "responseBody",
        label: "Response Body",
        type: "textarea",
        defaultValue: '{"status":"ok","source":"test-fixture"}',
      },
    ],
    previewFields: ["responseBody"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
  {
    type: "outputNode",
    title: "Output",
    description: "Emit the final output from the graph.",
    pack: "observability",
    category: "Output",
    icon: "TerminalSquare",
    colorClass: "bg-green-500/10 text-green-400 border-green-500/20",
    inputs: [{ id: "default", label: "Input", schema: "json" }],
    outputs: [{ id: "default", label: "Output", schema: "json" }],
    fields: [{ name: "label", label: "Label", type: "text", defaultValue: "Output" }],
    previewFields: ["label"],
    capabilities: { design: true, analyze: true, simulate: true, execute: true },
  },
];

export const NODE_DEFINITION_MAP = Object.fromEntries(
  NODE_DEFINITIONS.map((definition) => [definition.type, definition])
) as Record<string, NodeDefinition>;

export const NODE_PACK_ORDER = [
  "ai",
  "backend",
  "data",
  "reliability",
  "security",
  "observability",
] as const;

export function getNodeDefinition(type: string) {
  return NODE_DEFINITION_MAP[type];
}

export function getDefaultNodeData(type: string) {
  const definition = getNodeDefinition(type);
  if (!definition) return { label: type };

  const defaults: Record<string, unknown> = {};
  for (const field of definition.fields) {
    if (field.defaultValue !== undefined) {
      defaults[field.name] = field.defaultValue;
    }
  }
  if (!defaults.label) {
    defaults.label = definition.title;
  }
  return defaults;
}
